### ISSUE TITLE
Face cropping is to slow and generate the following warning message!

### ISSUE THREAD

**Issue by Falmi** [fuankarion/active-speakers-context#12]
Why is it very slow? Though it is generating a cropped face, it shows the following warning message. Does it something related to the speed? 
![image](https://user-images.githubusercontent.com/26068376/100846631-b5e1cb80-34b9-11eb-914f-b1a94f90dca2.png)

**Comment by fuankarion** [comment]
Hi, 
Face crop extraction is kind of slow and we never optimized it as it is a 1 time process, it might take 1 or 2 days.
That error message will appear occasionally, but the files will be extracted properly into the destination directory.
