### ISSUE TITLE
STE_postprocessing.py files 

### ISSUE THREAD

**Issue by Andrew-Brown1** [fuankarion/active-speakers-context#16]
Hi,
Thanks for this very clean and easy-to-use repo! 

I was wondering, in STE_postprocessing.py on lines 49 and 50. where do "STE.csv" and "gt.csv" come from? 

I have done the forward pass of the STE, and the predictions are stored in "forward_dir" (line 44) 

Thanks for your help!

**Comment by fuankarion** [comment]
Hi, 

This one is poorly documented. The CSVs that you mention are created by the script, these two in particular are the ones you would use as input to the official evaluation tool. I just updated the Readme with some info in this regard.
