### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by rahulranjan29** [fuankarion/active-speakers-context#2]
Hi, Thanks for the open source code, I was wondering what time did it take to train the ASC model? Also, Can you please upload the model weight if possible . Thanks!

**Comment by fuankarion** [comment]
Hi, the model itself is rather lightweight and both stages (STE & ASC) can be trained on single day with a TitanX GPU. 
I just relized the models are missing, I'll be working on that this week.

**Comment by rahulranjan29** [comment]
Hi, Thanks for the update :)
