### ISSUE TITLE
What does instance_id mean?

### ISSUE THREAD

**Issue by ArialChan** [fuankarion/active-speakers-context#21]
Thank you for sharing your code.

What does instance_id mean? in csv file?   (ex: vL7N_xRJKJU_1440_1500:118:0:0)
I need this information to train my own data.

Thanks and looking forward for your reply.

**Comment by fuankarion** [comment]
Hi

entity_id and instance_id are related. While entity_id identifies a single tracklet in the dataset, instance_id creates a division on a tracklet everytime the groundtruth changes. That is, you split the tracklet into "sub-tracklets'', each subtraclet is guaranteed to have the same speech activity (silent or speaking).

**Comment by ArialChan** [comment]
Thank you for your help!
