### ISSUE TITLE
ASC_forward.py is missing

### ISSUE THREAD

**Issue by chrismbirmingham** [fuankarion/active-speakers-context#3]
I am training a model from scratch and it is nearly done, however I checked and ASC_forward.py appears to be a copy of the README, do you mind updating it? I am very excited about using your work in a HRI research context but need some help with reproducing your results. Thanks for your great work!

**Comment by fuankarion** [comment]
Wow, my bad there. I'll have to rewrite it as I can't find a simmilar file that works for this code base. Check back soon.

**Comment by chrismbirmingham** [comment]
Will do! Thanks for the quick reply!!

**Comment by rahulranjan29** [comment]
@chrismbirmingham  Hi Chris, Mind if I ask you whether you can share the trained weights in a google drive or something? Thanks :)

**Comment by chrismbirmingham** [comment]
I don't mind, assuming I get something with reasonable performance! I'll
need to get ASC_forward first though.

**Comment by chrismbirmingham** [comment]
Just wanted to bump this request and let you know I have replicated the other training steps up the ASC_forward, just need the last step. I really appreciate your help!

**Comment by fuankarion** [comment]
Hi, Sorry you had to bump this one, I just wanted to test the results and code, not to create more unncesary issues.  Check the most recent version
