### ISSUE TITLE
Model Inputs

### ISSUE THREAD

**Issue by chrismbirmingham** [fuankarion/active-speakers-context#5]
Hi, I am attempting to set up the model for real world use and struggling to reverse engineer your dataset loader. From what I understand, the model should take 11 rgb face crops (144x144) as video_data (which also needs to be normalized), but how do you properly generate the audio input? I understand you are working with Mel Frequency Cepstral Coefficients, but can you give me some insight on why 11 frames worth of audio would match with an input shape of 13x40?

**Comment by fuankarion** [comment]
Hi, 

The idea pretty straightforward but got rather complicated while trying to save some time/resources: 

First, you load a 'videoclip' with 11 (consecutive) face crops, and define a temporal window [ti,..., tj, ..., tk] ti corresponds to the timestamp of the first face crop, and tk the timestamp of the last facecrop. tj would be the frame right at the middle and we use this one as the label for the clip. This timestamps are provided in the csv.

Then, you  load the audio data in between ti and tk, the catch is that fps rate for AVA Active Speaker is **semi-standard** so most videos yield and array of almost the same size (6400 positions IIRC). As the array is almost always the same size the spectrogram has almost always the same (11*40) size for clips of 11 frames.

So 11 video frames span about 0.45 seconds, which map to about 6400 audio samples which turn into an 11*40 spectrogram.

BTW, occasionally you will find shorter audio sequences for 11 frames (again the semi-standard fps), we just pad those sequences.

**Comment by chrismbirmingham** [comment]
Awesome, thanks for the help! In a similar vein, how do you parse the output of the STE? For a binary classification would you take the argmax of the two outputs? In which I am assuming max in position 0 would be not talking and max in position 1 would be talking?

**Comment by fuankarion** [comment]
We have a specific postprocessing for that in ./STE_postprocessing.py
Now I realize that it is not documented at all. I'll catch up to that.
